"""Add repomap modes

Revision ID: 3890cbcf8415
Revises: dafaa737d147
Create Date: 2026-01-30 06:39:22.704414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3890cbcf8415'
down_revision: Union[str, Sequence[str], None] = 'dafaa737d147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repomap_mode', sa.Enum('AUTO', 'TREE', 'MANUAL', name='repomapmode'), nullable=False, server_default='AUTO'))
        batch_op.add_column(sa.Column('repomap_ignore_patterns', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('repomap_ignore_patterns')
        batch_op.drop_column('repomap_mode')
    # ### end Alembic commands ###
