"""Add workflow blob context

Revision ID: 62f1f2117d93
Revises: cd8809a6483f
Create Date: 2025-11-25 12:45:03.155016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f1f2117d93'
down_revision: Union[str, Sequence[str], None] = 'cd8809a6483f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_states',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(
        ['session_id'],
        ['chat_sessions.id'],
        name='fk_workflow_states_session_id_chat_sessions',
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_states')
    # ### end Alembic commands ###
