"""Remove redundant tool_calls and content from Message

Revision ID: 6f516321b2ce
Revises: 9c9130fab590
Create Date: 2025-12-16 18:06:56.252121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6f516321b2ce'
down_revision: Union[str, Sequence[str], None] = '9c9130fab590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_calls')
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.TEXT(), nullable=False))
    op.add_column('messages', sa.Column('tool_calls', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
