"""Update settings llm fields

Revision ID: 794aaab4a398
Revises: ab6e35d580ae
Create Date: 2025-12-01 11:28:09.935486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794aaab4a398'
down_revision: Union[str, Sequence[str], None] = 'ab6e35d580ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_role', sa.Enum('CODER', name='llmrole'), nullable=True))
        batch_op.create_unique_constraint('uq_llm_settings_active_role', ['active_role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_llm_settings_active_role', type_='unique')
        batch_op.drop_column('active_role')
    # ### end Alembic commands ###
