"""Update llm settings

Revision ID: 91b3671b1f87
Revises: f976d56d3b63
Create Date: 2025-11-01 18:07:51.371813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b3671b1f87'
down_revision: Union[str, Sequence[str], None] = 'f976d56d3b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("coding_llm_temperature", sa.Float(), nullable=False, server_default="0.7"))

    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provider", sa.Enum("ANTHROPIC", "GOOGLE", "OPENAI"), nullable=False, server_default="OPENAI"))
        batch_op.add_column(sa.Column("api_key", sa.String(), nullable=True))

    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_constraint("_model_temperature_uc", type_="unique")
        batch_op.create_unique_constraint("_model_name_uc", ["model_name"])
        batch_op.drop_column("temperature")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("coding_llm_temperature")

    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("temperature", sa.FLOAT(), nullable=False, server_default="0.7"))
        batch_op.drop_constraint("_model_name_uc", type_="unique")
        batch_op.create_unique_constraint("_model_temperature_uc", ["model_name", "temperature"])

    with op.batch_alter_table("llm_settings", schema=None) as batch_op:
        batch_op.drop_column("api_key")
        batch_op.drop_column("provider")
    # ### end Alembic commands ###
