"""Add block based rendering and remove diff patch

Revision ID: 9c9130fab590
Revises: b71f51e9a21c
Create Date: 2025-12-16 12:35:41.538947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9c9130fab590'
down_revision: Union[str, Sequence[str], None] = 'b71f51e9a21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('blocks', sa.JSON(), server_default='[]', nullable=False))
    op.drop_column('messages', 'diff_patches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('diff_patches', sqlite.JSON(), nullable=True))
    op.drop_column('messages', 'blocks')
    # ### end Alembic commands ###
