"""Add usage models

Revision ID: ab6e35d580ae
Revises: 62f1f2117d93
Create Date: 2025-11-29 15:41:55.382299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6e35d580ae'
down_revision: Union[str, Sequence[str], None] = '62f1f2117d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_provider_usage',
    sa.Column('provider', sa.String(), nullable=False),
        sa.Column('total_cost', sa.Float(), nullable=False, server_default='0'),
        sa.Column('total_input_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_output_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_cached_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('provider'),
    )

    op.create_table(
        'session_usage',
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('cost', sa.Float(), nullable=False, server_default='0'),
        sa.Column('input_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('output_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('cached_tokens', sa.Integer(), nullable=False, server_default='0'),
        sa.ForeignKeyConstraint(
            ['session_id'],
            ['chat_sessions.id'],
            name='fk_session_usage_session_id_chat_sessions',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('session_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_usage')
    op.drop_table('global_provider_usage')
    # ### end Alembic commands ###
