"""Add json fields for tool exhibition

Revision ID: b71f51e9a21c
Revises: 794aaab4a398
Create Date: 2025-12-09 19:28:00.869907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71f51e9a21c'
down_revision: Union[str, Sequence[str], None] = '794aaab4a398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('diff_patches', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'diff_patches')
    op.drop_column('messages', 'tool_calls')
    # ### end Alembic commands ###
