"""Add session Operational Modes and diff ui setting

Revision ID: c2d757907f05
Revises: fe9dafedda8f
Create Date: 2025-12-25 17:17:20.443027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d757907f05'
down_revision: Union[str, Sequence[str], None] = 'fe9dafedda8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diff_patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('diff_original', sa.Text(), nullable=False),
    sa.Column('diff_current', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'REJECTED', 'FAILED', name='patchstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('tool_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diff_patches_id'), 'diff_patches', ['id'], unique=False)
    op.create_index(op.f('ix_diff_patches_session_id'), 'diff_patches', ['session_id'], unique=False)
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'operational_mode',
                sa.Enum('CODING', 'ASK', 'CHAT', 'PLANNER', 'SINGLE_SHOT', name='operationalmode'),
                server_default='CODING',
                nullable=False,
            )
        )

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diff_patches_auto_open', sa.Boolean(), server_default='t', nullable=False))
        batch_op.alter_column(
            'operational_mode',
            existing_type=sa.VARCHAR(length=9),
            type_=sa.Enum('CODING', 'ASK', 'CHAT', 'PLANNER', 'SINGLE_SHOT', name='operationalmode'),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column(
            'operational_mode',
            existing_type=sa.Enum('CODING', 'ASK', 'CHAT', 'PLANNER', 'SINGLE_SHOT', name='operationalmode'),
            type_=sa.VARCHAR(length=9),
            existing_nullable=False,
        )
        batch_op.drop_column('diff_patches_auto_open')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('operational_mode')

    op.drop_index(op.f('ix_diff_patches_session_id'), table_name='diff_patches')
    op.drop_index(op.f('ix_diff_patches_id'), table_name='diff_patches')
    op.drop_table('diff_patches')
    # ### end Alembic commands ###