"""Add context files

Revision ID: cd8809a6483f
Revises: 123a789273fe
Create Date: 2025-11-24 20:09:29.860272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8809a6483f'
down_revision: Union[str, Sequence[str], None] = '123a789273fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('context_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('context_files', sa.Column('user_pinned', sa.Boolean(), nullable=True))
    op.add_column('context_files', sa.Column('hit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_files', 'hit_count')
    op.drop_column('context_files', 'user_pinned')
    op.drop_column('context_files', 'updated_at')
    op.drop_column('context_files', 'created_at')
    # ### end Alembic commands ###
