"""Update message role enum

Revision ID: e3946c800f09
Revises: 62f1f2117d93
Create Date: 2025-11-29 07:33:57.918751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3946c800f09'
down_revision: Union[str, Sequence[str], None] = '62f1f2117d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=4),
                   type_=sa.Enum('USER', 'AI', 'SYSTEM', name='messagerole'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('role',
                   existing_type=sa.Enum('USER', 'AI', 'SYSTEM', name='messagerole'),
                   type_=sa.VARCHAR(length=4),
                   existing_nullable=False)
    # ### end Alembic commands ###