"""Add token limits for grep

Revision ID: fe9dafedda8f
Revises: 6f516321b2ce
Create Date: 2025-12-19 10:48:15.496697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9dafedda8f'
down_revision: Union[str, Sequence[str], None] = '6f516321b2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grep_token_limit', sa.Integer(), nullable=False, server_default='4000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('grep_token_limit')
    # ### end Alembic commands ###